baseURL: "https://ai.ragv.in"
languageCode: "en-us"
title: "AI Logs"
theme: "PaperMod"
googleAnalytics: G-RGHWYFE1WN
enableEmoji: true
privacy:
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
    useSessionStorage: false
copyright: © 2022 [Raghava Dhanya](https://ragv.in) | [License](/license) |
params:
  # cover:
  #   hidden: false
  env: production
  author: "Raghava Dhanya"
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  homeInfoParams:
    Title: "AI Logs"
    Content: >
      - Logs on all things Machine Learning, Artificial intellgence and MLOps

      - By [Raghava Dhanya](https://ragv.in)

  socialIcons:
    - name: other
      url: "https://ragv.in"
    - name: twitter
      url: "https://twitter.com/RaghavaDhanya"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/4755194/raghavadhanya"
    - name: github
      url: "https://github.com/RaghavaDhanya"
    - name: linkedin
      url: "https://www.linkedin.com/in/raghavadhanya/"
    - name: cv
      url: "https://ragv.in/s/resume"
    - name: email
      url: "mailto:public@ragv.in"
    - name: rss
      url: /index.xml
menu:
  main:
    - identifier: project
      name: projects
      url: /categories/projects/
      weight: 10
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 10
    - identifier: ragv.in
      name: ragv.in
      url: https://ragv.in
      weight: 20
